module Evergreen.Migrate.V11 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V11.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V11.Types.FrontendModel Evergreen.V11.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V11.Types.BackendModel Evergreen.V11.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V11.Types.FrontendMsg Evergreen.V11.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V11.Types.ToBackend Evergreen.V11.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V11.Types.BackendMsg Evergreen.V11.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V11.Types.ToFrontend Evergreen.V11.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V11.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , userProgress = old.userProgress
    , puzzleInput = old.puzzleInput
    , lastAnswerResult = old.lastAnswerResult |> migrate_Types_AnswerResult
    }


migrate_Types_AnswerResult : Evergreen.V1.Types.AnswerResult -> Evergreen.V11.Types.AnswerResult
migrate_Types_AnswerResult old =
    case old of
        Evergreen.V1.Types.NoAnswerYet ->
            Evergreen.V11.Types.NoAnswerYet

        Evergreen.V1.Types.Incorrect p0 ->
            Evergreen.V11.Types.Incorrect (p0 |> migrate_Types_PuzzleId)

        Evergreen.V1.Types.Correct p0 p1 ->
            Evergreen.V11.Types.Correct (p0 |> migrate_Types_PuzzleId) p1


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V11.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V11.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V11.Types.UrlChanged p0

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V11.Types.NoOpFrontendMsg

        Evergreen.V1.Types.PuzzleInputChanged p0 ->
            Evergreen.V11.Types.PuzzleInputChanged p0

        Evergreen.V1.Types.SubmitAnswer p0 ->
            Evergreen.V11.Types.SubmitAnswer (p0 |> migrate_Types_PuzzleId)

        Evergreen.V1.Types.ClickedBegin ->
            Evergreen.V11.Types.ClickedBegin

        Evergreen.V1.Types.NavigateTo p0 ->
            Evergreen.V11.Types.NavigateTo p0


migrate_Types_PuzzleId : Evergreen.V1.Types.PuzzleId -> Evergreen.V11.Types.PuzzleId
migrate_Types_PuzzleId old =
    case old of
        Evergreen.V1.Types.Puzzle1 ->
            Evergreen.V11.Types.Puzzle1

        Evergreen.V1.Types.Puzzle2 ->
            Evergreen.V11.Types.Puzzle2

        Evergreen.V1.Types.Puzzle3 ->
            Evergreen.V11.Types.Puzzle3

        Evergreen.V1.Types.Puzzle4 ->
            Evergreen.V11.Types.Puzzle4


migrate_Types_Route : Evergreen.V1.Types.Route -> Evergreen.V11.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V1.Types.IntroRoute ->
            Evergreen.V11.Types.IntroRoute

        Evergreen.V1.Types.HubRoute ->
            Evergreen.V11.Types.HubRoute

        Evergreen.V1.Types.PaintingsRoute ->
            Evergreen.V11.Types.PaintingsRoute

        Evergreen.V1.Types.LedgerRoute ->
            Evergreen.V11.Types.LedgerRoute

        Evergreen.V1.Types.StashRoute ->
            Evergreen.V11.Types.StashRoute

        Evergreen.V1.Types.StashFoundRoute p0 ->
            Evergreen.V11.Types.StashFoundRoute (p0 |> migrate_Types_StashId)

        Evergreen.V1.Types.TileRoute ->
            Evergreen.V11.Types.TileRoute

        Evergreen.V1.Types.NotFoundRoute ->
            Evergreen.V11.Types.NotFoundRoute


migrate_Types_StashId : Evergreen.V1.Types.StashId -> Evergreen.V11.Types.StashId
migrate_Types_StashId old =
    case old of
        Evergreen.V1.Types.Moonshine ->
            Evergreen.V11.Types.Moonshine

        Evergreen.V1.Types.Whiskey ->
            Evergreen.V11.Types.Whiskey

        Evergreen.V1.Types.Gin ->
            Evergreen.V11.Types.Gin

        Evergreen.V1.Types.Bourbon ->
            Evergreen.V11.Types.Bourbon

        Evergreen.V1.Types.Rum ->
            Evergreen.V11.Types.Rum


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V11.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.MarkIntroSeen ->
            Evergreen.V11.Types.MarkIntroSeen

        Evergreen.V1.Types.SubmitPuzzleAnswer p0 p1 ->
            Evergreen.V11.Types.SubmitPuzzleAnswer (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V1.Types.MarkStashFound p0 ->
            Evergreen.V11.Types.MarkStashFound (p0 |> migrate_Types_StashId)
