module Evergreen.Migrate.V13 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V11.Types
import Evergreen.V13.Types
import Lamdera.Migrations exposing (..)
import Maybe
import SeqDict


frontendModel : Evergreen.V11.Types.FrontendModel -> ModelMigration Evergreen.V13.Types.FrontendModel Evergreen.V13.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V11.Types.BackendModel -> ModelMigration Evergreen.V13.Types.BackendModel Evergreen.V13.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V11.Types.FrontendMsg -> MsgMigration Evergreen.V13.Types.FrontendMsg Evergreen.V13.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V11.Types.ToBackend -> MsgMigration Evergreen.V13.Types.ToBackend Evergreen.V13.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V11.Types.BackendMsg -> MsgMigration Evergreen.V13.Types.BackendMsg Evergreen.V13.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V11.Types.ToFrontend -> MsgMigration Evergreen.V13.Types.ToFrontend Evergreen.V13.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V11.Types.BackendModel -> Evergreen.V13.Types.BackendModel
migrate_Types_BackendModel old =
    { userProgress = old.userProgress |> SeqDict.map (\k -> migrate_Types_UserProgress)
    , sessionClients = SeqDict.empty
    }


migrate_Types_FrontendModel : Evergreen.V11.Types.FrontendModel -> Evergreen.V13.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , userProgress = old.userProgress |> Maybe.map migrate_Types_UserProgress
    , puzzleInput = old.puzzleInput
    , lastAnswerResult = old.lastAnswerResult |> migrate_Types_AnswerResult
    }


migrate_Types_AnswerResult : Evergreen.V11.Types.AnswerResult -> Evergreen.V13.Types.AnswerResult
migrate_Types_AnswerResult old =
    case old of
        Evergreen.V11.Types.NoAnswerYet ->
            Evergreen.V13.Types.NoAnswerYet

        Evergreen.V11.Types.Incorrect p0 ->
            Evergreen.V13.Types.Incorrect (p0 |> migrate_Types_PuzzleId)

        Evergreen.V11.Types.Correct p0 p1 ->
            Evergreen.V13.Types.Correct (p0 |> migrate_Types_PuzzleId) p1


migrate_Types_FrontendMsg : Evergreen.V11.Types.FrontendMsg -> Evergreen.V13.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V11.Types.UrlClicked p0 ->
            Evergreen.V13.Types.UrlClicked p0

        Evergreen.V11.Types.UrlChanged p0 ->
            Evergreen.V13.Types.UrlChanged p0

        Evergreen.V11.Types.NoOpFrontendMsg ->
            Evergreen.V13.Types.NoOpFrontendMsg

        Evergreen.V11.Types.PuzzleInputChanged p0 ->
            Evergreen.V13.Types.PuzzleInputChanged p0

        Evergreen.V11.Types.SubmitAnswer p0 ->
            Evergreen.V13.Types.SubmitAnswer (p0 |> migrate_Types_PuzzleId)

        Evergreen.V11.Types.ClickedBegin ->
            Evergreen.V13.Types.ClickedBegin

        Evergreen.V11.Types.NavigateTo p0 ->
            Evergreen.V13.Types.NavigateTo p0

        Evergreen.V11.Types.Tick ->
            Evergreen.V13.Types.Tick


migrate_Types_PuzzleId : Evergreen.V11.Types.PuzzleId -> Evergreen.V13.Types.PuzzleId
migrate_Types_PuzzleId old =
    case old of
        Evergreen.V11.Types.Puzzle1 ->
            Evergreen.V13.Types.Puzzle1

        Evergreen.V11.Types.Puzzle2 ->
            Evergreen.V13.Types.Puzzle2

        Evergreen.V11.Types.Puzzle3 ->
            Evergreen.V13.Types.Puzzle3

        Evergreen.V11.Types.Puzzle4 ->
            -- Puzzle4 was removed; migrate to Puzzle3 as fallback
            Evergreen.V13.Types.Puzzle3


migrate_Types_Route : Evergreen.V11.Types.Route -> Evergreen.V13.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V11.Types.IntroRoute ->
            Evergreen.V13.Types.IntroRoute

        Evergreen.V11.Types.HubRoute ->
            Evergreen.V13.Types.HubRoute

        Evergreen.V11.Types.PaintingsRoute ->
            Evergreen.V13.Types.PaintingsRoute

        Evergreen.V11.Types.LedgerRoute ->
            Evergreen.V13.Types.LedgerRoute

        Evergreen.V11.Types.StashRoute ->
            Evergreen.V13.Types.StashRoute

        Evergreen.V11.Types.StashFoundRoute p0 ->
            Evergreen.V13.Types.StashFoundRoute (p0 |> migrate_Types_StashId)

        Evergreen.V11.Types.TileRoute ->
            -- TileRoute was removed; redirect to NotFoundRoute
            Evergreen.V13.Types.NotFoundRoute

        Evergreen.V11.Types.HelpRoute ->
            Evergreen.V13.Types.HelpRoute

        Evergreen.V11.Types.NotFoundRoute ->
            Evergreen.V13.Types.NotFoundRoute


migrate_Types_StashId : Evergreen.V11.Types.StashId -> Evergreen.V13.Types.StashId
migrate_Types_StashId old =
    case old of
        Evergreen.V11.Types.Moonshine ->
            Evergreen.V13.Types.Moonshine

        Evergreen.V11.Types.Whiskey ->
            Evergreen.V13.Types.Whiskey

        Evergreen.V11.Types.Gin ->
            Evergreen.V13.Types.Gin

        Evergreen.V11.Types.Bourbon ->
            Evergreen.V13.Types.Bourbon

        Evergreen.V11.Types.Rum ->
            Evergreen.V13.Types.Rum


migrate_Types_StashProgress : Evergreen.V11.Types.StashProgress -> Evergreen.V13.Types.StashProgress
migrate_Types_StashProgress old =
    old


migrate_Types_ToBackend : Evergreen.V11.Types.ToBackend -> Evergreen.V13.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V11.Types.RequestInitialState ->
            Evergreen.V13.Types.RequestInitialState

        Evergreen.V11.Types.MarkIntroSeen ->
            Evergreen.V13.Types.MarkIntroSeen

        Evergreen.V11.Types.SubmitPuzzleAnswer p0 p1 ->
            Evergreen.V13.Types.SubmitPuzzleAnswer (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V11.Types.MarkStashFound p0 ->
            Evergreen.V13.Types.MarkStashFound (p0 |> migrate_Types_StashId)


migrate_Types_ToFrontend : Evergreen.V11.Types.ToFrontend -> Evergreen.V13.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V11.Types.InitialState p0 ->
            Evergreen.V13.Types.InitialState (p0 |> migrate_Types_UserProgress)

        Evergreen.V11.Types.PuzzleAnswerResult p0 p1 ->
            Evergreen.V13.Types.PuzzleAnswerResult (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V11.Types.StashMarked p0 ->
            Evergreen.V13.Types.StashMarked (p0 |> migrate_Types_StashId)


migrate_Types_UserProgress : Evergreen.V11.Types.UserProgress -> Evergreen.V13.Types.UserProgress
migrate_Types_UserProgress old =
    { hasSeenIntro = old.hasSeenIntro
    , puzzle1Complete = old.puzzle1Complete
    , puzzle2Complete = old.puzzle2Complete
    , puzzle3Stashes = old.puzzle3Stashes |> migrate_Types_StashProgress
    , puzzle3Complete = old.puzzle3Complete
    -- puzzle4Complete field was removed, dropping data
    }
