module Evergreen.Migrate.V14 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V13.Types
import Evergreen.V14.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V13.Types.FrontendModel -> ModelMigration Evergreen.V14.Types.FrontendModel Evergreen.V14.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V13.Types.BackendModel -> ModelMigration Evergreen.V14.Types.BackendModel Evergreen.V14.Types.BackendMsg
backendModel _ =
    ModelUnchanged


frontendMsg : Evergreen.V13.Types.FrontendMsg -> MsgMigration Evergreen.V14.Types.FrontendMsg Evergreen.V14.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V13.Types.ToBackend -> MsgMigration Evergreen.V14.Types.ToBackend Evergreen.V14.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V13.Types.BackendMsg -> MsgMigration Evergreen.V14.Types.BackendMsg Evergreen.V14.Types.BackendMsg
backendMsg _ =
    MsgUnchanged


toFrontend : Evergreen.V13.Types.ToFrontend -> MsgMigration Evergreen.V14.Types.ToFrontend Evergreen.V14.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V13.Types.FrontendModel -> Evergreen.V14.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , userProgress = old.userProgress
    , puzzleInput = old.puzzleInput
    , lastAnswerResult = old.lastAnswerResult |> migrate_Types_AnswerResult
    }


migrate_Types_AnswerResult : Evergreen.V13.Types.AnswerResult -> Evergreen.V14.Types.AnswerResult
migrate_Types_AnswerResult old =
    case old of
        Evergreen.V13.Types.NoAnswerYet ->
            Evergreen.V14.Types.NoAnswerYet

        Evergreen.V13.Types.Incorrect p0 ->
            Evergreen.V14.Types.Incorrect (p0 |> migrate_Types_PuzzleId)

        Evergreen.V13.Types.Correct p0 p1 ->
            Evergreen.V14.Types.Correct (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V13.Types.IncorrectButClose p0 ->
            Evergreen.V14.Types.IncorrectButClose (p0 |> migrate_Types_PuzzleId)


migrate_Types_FrontendMsg : Evergreen.V13.Types.FrontendMsg -> Evergreen.V14.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V13.Types.UrlClicked p0 ->
            Evergreen.V14.Types.UrlClicked p0

        Evergreen.V13.Types.UrlChanged p0 ->
            Evergreen.V14.Types.UrlChanged p0

        Evergreen.V13.Types.NoOpFrontendMsg ->
            Evergreen.V14.Types.NoOpFrontendMsg

        Evergreen.V13.Types.PuzzleInputChanged p0 ->
            Evergreen.V14.Types.PuzzleInputChanged p0

        Evergreen.V13.Types.SubmitAnswer p0 ->
            Evergreen.V14.Types.SubmitAnswer (p0 |> migrate_Types_PuzzleId)

        Evergreen.V13.Types.ClickedBegin ->
            Evergreen.V14.Types.ClickedBegin

        Evergreen.V13.Types.NavigateTo p0 ->
            Evergreen.V14.Types.NavigateTo p0

        Evergreen.V13.Types.Tick ->
            Evergreen.V14.Types.Tick


migrate_Types_PuzzleId : Evergreen.V13.Types.PuzzleId -> Evergreen.V14.Types.PuzzleId
migrate_Types_PuzzleId old =
    case old of
        Evergreen.V13.Types.Puzzle1 ->
            Evergreen.V14.Types.Puzzle1

        Evergreen.V13.Types.Puzzle2 ->
            Evergreen.V14.Types.Puzzle2

        Evergreen.V13.Types.Puzzle3 ->
            Evergreen.V14.Types.Puzzle3


migrate_Types_Route : Evergreen.V13.Types.Route -> Evergreen.V14.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V13.Types.IntroRoute ->
            Evergreen.V14.Types.IntroRoute

        Evergreen.V13.Types.HubRoute ->
            Evergreen.V14.Types.HubRoute

        Evergreen.V13.Types.PaintingsRoute ->
            Evergreen.V14.Types.PaintingsRoute

        Evergreen.V13.Types.LedgerRoute ->
            Evergreen.V14.Types.LedgerRoute

        Evergreen.V13.Types.StashRoute ->
            Evergreen.V14.Types.StashRoute

        Evergreen.V13.Types.StashFoundRoute p0 ->
            Evergreen.V14.Types.StashFoundRoute (p0 |> migrate_Types_StashId)

        Evergreen.V13.Types.HelpRoute ->
            Evergreen.V14.Types.HelpRoute

        Evergreen.V13.Types.NotFoundRoute ->
            Evergreen.V14.Types.NotFoundRoute


migrate_Types_StashId : Evergreen.V13.Types.StashId -> Evergreen.V14.Types.StashId
migrate_Types_StashId old =
    case old of
        Evergreen.V13.Types.Moonshine ->
            Evergreen.V14.Types.Moonshine

        Evergreen.V13.Types.Whiskey ->
            Evergreen.V14.Types.Whiskey

        Evergreen.V13.Types.Gin ->
            Evergreen.V14.Types.Gin

        Evergreen.V13.Types.Bourbon ->
            Evergreen.V14.Types.Bourbon

        Evergreen.V13.Types.Rum ->
            Evergreen.V14.Types.Rum


migrate_Types_StashProgress : Evergreen.V13.Types.StashProgress -> Evergreen.V14.Types.StashProgress
migrate_Types_StashProgress old =
    old


migrate_Types_ToBackend : Evergreen.V13.Types.ToBackend -> Evergreen.V14.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V13.Types.RequestInitialState ->
            Evergreen.V14.Types.RequestInitialState

        Evergreen.V13.Types.MarkIntroSeen ->
            Evergreen.V14.Types.MarkIntroSeen

        Evergreen.V13.Types.SubmitPuzzleAnswer p0 p1 ->
            Evergreen.V14.Types.SubmitPuzzleAnswer (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V13.Types.MarkStashFound p0 ->
            Evergreen.V14.Types.MarkStashFound (p0 |> migrate_Types_StashId)


migrate_Types_ToFrontend : Evergreen.V13.Types.ToFrontend -> Evergreen.V14.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V13.Types.InitialState p0 ->
            Evergreen.V14.Types.InitialState (p0 |> migrate_Types_UserProgress)

        Evergreen.V13.Types.PuzzleAnswerResult p0 p1 ->
            Evergreen.V14.Types.PuzzleAnswerResult (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V13.Types.StashMarked p0 ->
            Evergreen.V14.Types.StashMarked (p0 |> migrate_Types_StashId)


migrate_Types_UserProgress : Evergreen.V13.Types.UserProgress -> Evergreen.V14.Types.UserProgress
migrate_Types_UserProgress old =
    { hasSeenIntro = old.hasSeenIntro
    , puzzle1Complete = old.puzzle1Complete
    , puzzle2Complete = old.puzzle2Complete
    , puzzle3Stashes = old.puzzle3Stashes |> migrate_Types_StashProgress
    , puzzle3Complete = old.puzzle3Complete
    }
