module Evergreen.Migrate.V18 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V14.Types
import Evergreen.V18.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V14.Types.FrontendModel -> ModelMigration Evergreen.V18.Types.FrontendModel Evergreen.V18.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V14.Types.BackendModel -> ModelMigration Evergreen.V18.Types.BackendModel Evergreen.V18.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V14.Types.FrontendMsg -> MsgMigration Evergreen.V18.Types.FrontendMsg Evergreen.V18.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V14.Types.ToBackend -> MsgMigration Evergreen.V18.Types.ToBackend Evergreen.V18.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V14.Types.BackendMsg -> MsgMigration Evergreen.V18.Types.BackendMsg Evergreen.V18.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V14.Types.ToFrontend -> MsgMigration Evergreen.V18.Types.ToFrontend Evergreen.V18.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V14.Types.FrontendModel -> Evergreen.V18.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , userProgress = old.userProgress
    , puzzleInput = old.puzzleInput
    , lastAnswerResult = old.lastAnswerResult |> migrate_Types_AnswerResult
    }


migrate_Types_AnswerResult : Evergreen.V14.Types.AnswerResult -> Evergreen.V18.Types.AnswerResult
migrate_Types_AnswerResult old =
    case old of
        Evergreen.V14.Types.NoAnswerYet ->
            Evergreen.V18.Types.NoAnswerYet

        Evergreen.V14.Types.Incorrect p0 ->
            Evergreen.V18.Types.Incorrect (p0 |> migrate_Types_PuzzleId)

        Evergreen.V14.Types.Correct p0 p1 ->
            Evergreen.V18.Types.Correct (p0 |> migrate_Types_PuzzleId) p1

        Evergreen.V14.Types.IncorrectButClose p0 ->
            Evergreen.V18.Types.IncorrectButClose (p0 |> migrate_Types_PuzzleId)


migrate_Types_PuzzleId : Evergreen.V14.Types.PuzzleId -> Evergreen.V18.Types.PuzzleId
migrate_Types_PuzzleId old =
    case old of
        Evergreen.V14.Types.Puzzle1 ->
            Evergreen.V18.Types.Puzzle1

        Evergreen.V14.Types.Puzzle2 ->
            Evergreen.V18.Types.Puzzle2

        Evergreen.V14.Types.Puzzle3 ->
            Evergreen.V18.Types.Puzzle3


migrate_Types_Route : Evergreen.V14.Types.Route -> Evergreen.V18.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V14.Types.IntroRoute ->
            Evergreen.V18.Types.IntroRoute

        Evergreen.V14.Types.HubRoute ->
            Evergreen.V18.Types.HubRoute

        Evergreen.V14.Types.PaintingsRoute ->
            Evergreen.V18.Types.PaintingsRoute

        Evergreen.V14.Types.LedgerRoute ->
            Evergreen.V18.Types.LedgerRoute

        Evergreen.V14.Types.StashRoute ->
            Evergreen.V18.Types.StashRoute

        Evergreen.V14.Types.StashFoundRoute p0 ->
            Evergreen.V18.Types.StashFoundRoute (p0 |> migrate_Types_StashId)

        Evergreen.V14.Types.HelpRoute ->
            Evergreen.V18.Types.HelpRoute

        Evergreen.V14.Types.DebugResetRoute ->
            Evergreen.V18.Types.DebugResetRoute

        Evergreen.V14.Types.NotFoundRoute ->
            Evergreen.V18.Types.NotFoundRoute


migrate_Types_StashId : Evergreen.V14.Types.StashId -> Evergreen.V18.Types.StashId
migrate_Types_StashId old =
    case old of
        Evergreen.V14.Types.Moonshine ->
            Evergreen.V18.Types.Moonshine

        Evergreen.V14.Types.Whiskey ->
            Evergreen.V18.Types.Whiskey

        Evergreen.V14.Types.Gin ->
            Evergreen.V18.Types.Gin

        Evergreen.V14.Types.Bourbon ->
            Evergreen.V18.Types.Bourbon

        Evergreen.V14.Types.Rum ->
            Evergreen.V18.Types.Rum
